---
title: "C4C"
author: "Tyler Cobian"
date: "11/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages
```{r, include=FALSE}
library(gridExtra)
library(tidyverse)
library(here)
library(kableExtra)
library(ggpubr)
library(ggplot2)

```

Data

```{r, include=FALSE}

cotton<- read_csv(here("DATA", "cotton_combined.csv"))
cotton_climate_organic<-read.csv(here("DATA","cotton_organic_climate.csv")) %>% 
  mutate(GWP=dSOC*-44/12+CH4*16*28/12+N2O_flux*44*265/28)
kernza<- read_csv(here("DATA", "kernza_total.csv"))
kernza_updated<- read_csv(here("DATA", "kernza_updated.csv"))
kernza_compost<- read_csv(here("DATA", "Kernza_no_compost.csv"))
mango<- read_csv(here("DATA", "mango_total.csv"))
mango_compost<-read_csv(here("DATA", "MANGO_nutr_sens.csv"))
mango_crops<-read_csv(here("DATA", "MANGO_sens.csv")) %>% 
  mutate(GWP=dSOC*-44/12+CH4*16*28/12+N2O_flux*44*265/28)
mango_nc<- read_csv(here("DATA", "MANGO_total_noclimate.csv"))
bison_nc<- read_csv(here("DATA", "bison_total_no_climate.csv"))
bison<- read_csv(here("DATA", "bison_total.csv"))
bison_indi<- read_csv(here("DATA", "bison_individual_sensativity.csv"))
bison_comp<- read_csv(here("DATA", "bison_compiling_sensativity.csv"))
bison_grazing<- read_csv(here("DATA", "bison_grazing_sensativity.csv"))
all_data <- read_csv(here("DATA", "Total_Crops.csv"))
bison_nocompost<- read_csv(here("DATA", "regen_sd_no_compost.csv"))
bison_crop<-read_csv(here("DATA", "bison_compiling_sensativity.csv"))
SOC_change <- read_csv(here("DATA", "soc_change.csv"))
GWP_only <- read_csv(here("DATA", "GWP_total.csv"))


```

Graph #1 (Time Series SOC) AI
```{r}
# Need to update 

kernza_regen_SOC <- all_data %>% 
  filter(Country == "Minnesota",
         Practice == "Regenerative") %>% 
         group_by(Practice)

kernza_organic_SOC <- all_data %>% 
  filter(Country == "Minnesota",
         Practice == "Organic") %>% 
        group_by(Practice)

bison_regen_SOC <- all_data %>% 
  filter(Country == "South Dakota",
         Practice == "Regenerative") %>% 
         group_by(Practice)

bison_organic_SOC <- all_data %>% 
  filter(Country == "South Dakota",
         Practice == "Organic") %>% 
         group_by(Practice)

cotton_regen_SOC <- all_data %>% 
  filter(Country == "India",
         Practice == "Regenerative") %>% 
         group_by(Practice)

cotton_organic_SOC <- all_data %>% 
  filter(Country == "India",
         Practice == "Organic") %>% 
         group_by(Practice)

mango_regen_SOC <- all_data %>% 
  filter(Country == "Nicaragua",
         Practice == "Regenerative") %>% 
         group_by(Practice)

mango_organic_SOC <- all_data %>% 
  filter(Country == "Nicaragua",
         Practice == "Organic") %>% 
         group_by(Practice)

                   
# Kernza Graph

kernza_SOC <- ggplot()+
  geom_line(data = kernza_regen_SOC, aes(x = Year, y = End_SOC), col = "darkorchid4")+
  geom_text(aes(x = 16, y = 136000, label = "Regenerative"))+
  geom_line(data = kernza_organic_SOC, aes(x = Year, y = End_SOC), col = "darkorange2")+
  geom_text(aes(x = 16, y = 135300, label = "Organic"))+
  labs(title = "Kernza", y = "kgSOC/ha", x = element_blank())+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5)) # center the graph

kernza_SOC

# Bison Graph
  
bison_SOC <- ggplot()+
  geom_line(data = bison_regen_SOC, aes(x = Year, y = End_SOC), col = "darkorchid4")+
  geom_text(aes(x = 16, y = 35000, label = "Regenerative"))+
  geom_line(data = bison_organic_SOC, aes(x = Year, y = End_SOC), col = "darkorange2")+
  geom_text(aes(x = 16, y = 30000, label = "Organic"))+
  labs(title = "Bison", y = element_blank(), x = "Year")+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5)) # center the graph

bison_SOC

# Cotton Graph

cotton_SOC <- ggplot ()+
  geom_line(data = cotton_regen_SOC, aes(x = Year, y = End_SOC), col = "darkorchid4")+
  geom_text(aes(x = 13, y = 590000, label = "Regenerative"))+
  geom_line(data = cotton_organic_SOC, aes(x = Year, y = End_SOC), col = "darkorange2")+
  geom_text(aes(x = 14, y = 500000, label = "Organic"))+
  labs(title = "Cotton", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5)) # center the graph

cotton_SOC

# Mango Graph - figureout which file has gwp value

mango_SOC <- ggplot ()+
  geom_line(data = mango_regen_SOC, aes(x = Year, y = End_SOC), col = "darkorchid4")+
  geom_text(aes(x = 16, y = 210000, label = "Regenerative"))+
  geom_line(data = mango_organic_SOC, aes(x = Year, y = End_SOC), col = "darkorange2")+
  geom_text(aes(x = 16, y = 130000, label = "Organic"))+
  labs(title = "Mango", y = "kgSOC/ha")+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5)) # center the graph

mango_SOC

#### NEED TO ADD  FACET WRAP ####

SOC_plot <- plot(ggarrange(kernza_SOC, cotton_SOC, mango_SOC, bison_SOC))

SOC_plot


```

Graph #2 (Time Series GWP) AI
```{r}
 
# Kernza GWP
kernza_gwp <- ggplot()+
  geom_line(data = kernza_regen_SOC, aes(x = Year, y = GWP), col = "darkorchid4")+
  geom_text(aes(x = 16, y = 130, label = 'Regenerative'))+
  geom_line(data = kernza_organic_SOC, aes(x = Year, y = GWP), col = "darkorange2")+
  geom_text(aes(x = 16, y = 80, label = 'Organic'))+
  labs(title = "Kernza", y = "kgCO2e", x = element_blank())+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5)) # center the graph

kernza_gwp

# Bison GWP

bison_gwp <- ggplot()+
  geom_line(data = bison_regen_SOC, aes(x = Year, y = GWP), col = "darkorchid4")+
  geom_text(aes(x = 16, y = 1000, label = 'Regenerative'))+
  geom_line(data = bison_organic_SOC, aes(x = Year, y = GWP), col = "darkorange2")+
  geom_text(aes(x = 16, y = -300, label = 'Organic'))+
  labs(title = "Bison", y = element_blank())+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5)) # center the graph

bison_gwp

# Cotton GWP

cotton_gwp <- ggplot()+
  geom_line(data = cotton_regen_SOC, aes(x = Year, y = GWP), col = "darkorchid4")+
  geom_text(aes(x = 16, y = 60000, label = 'Regenerative'))+
  geom_line(data = cotton_organic_SOC, aes(x = Year, y = GWP), col = "darkorange2")+
  geom_text(aes(x = 16, y = 80000, label = 'Organic'))+
  labs(title = "Cotton", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5)) # center the graph

cotton_gwp

# Mango GWP

mango_gwp <- ggplot ()+
  geom_line(data = mango_regen_SOC, aes(x = Year, y = GWP), col = "darkorchid4")+
  geom_text(aes(x = 16, y = -10000, label = 'Regenerative'))+
  geom_line(data = mango_organic_SOC, aes(x = Year, y = GWP), col = "darkorange2")+
  geom_text(aes(x = 16, y = 22000, label = 'Organic'))+
  labs(title = "Mango", y = "Kg CO2e")+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5)) # center the graph

mango_gwp

gwp_plot <- plot(ggarrange(kernza_gwp, cotton_gwp, mango_gwp, bison_gwp))

gwp_plot


```

Graph #3 (Bar SOC & GWP) AI
```{r}

### SOC and GWP Cotton ### India

cotton_3_regen_soc <- sum(all_data$dSOC[217:234])
cotton_3_organic_soc <- sum(all_data$dSOC[145:162])

cotton_3_regen_gwp <- sum(all_data$GWP[217:234])
cotton_3_organic_gwp <- sum(all_data$GWP[145:162])

### Creating Data Frame and Plotting ###

### SOC ###

cotton_3_all <- data.frame(Practice = c("Regenerative", "Organic"),
                            SOC = c(cotton_3_regen_soc, cotton_3_organic_soc),
                            GWP = c(cotton_3_regen_gwp, cotton_3_organic_gwp))

cotton_all_soc <- ggplot(cotton_3_all, aes(y = SOC, x = Practice, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("deepskyblue4", "deepskyblue"))+
  labs(title = "Cotton", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  theme(plot.title = element_text(hjust = 0.5))

cotton_all_soc

### GWP ###

cotton_all_gwp <- ggplot(cotton_3_all, aes(y = GWP, x = Practice, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("deepskyblue4", "deepskyblue"))+
  labs(title = "Cotton", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  theme(plot.title = element_text(hjust = 0.5))

cotton_all_gwp

### SOC & GWP Kernza ### Minnesota

kernza_3_regen_soc<- sum(all_data$dSOC[55:72])
kernza_3_organic_soc <- sum(all_data$dSOC[37:54])

kernza_3_regen_gwp<- sum(all_data$GWP[55:72])
kernza_3_organic_gwp <- sum(all_data$GWP[37:54])

### Creating Data Frame and Plotting ###

kernza_3_all <- data.frame(Practice = c("Regenerative", "Organic"),
                            SOC = c(kernza_3_regen_soc, kernza_3_organic_soc),
                            GWP = c(kernza_3_regen_gwp, kernza_3_organic_gwp))

### SOC ###

kernza_all_soc <- ggplot(kernza_3_all, aes(y = SOC, x = Practice, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c ("aquamarine4", "aquamarine"))+
  labs(title = "Kernza", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  theme(plot.title = element_text(hjust = 0.5))
kernza_all_soc

### GWP ###

kernza_all_gwp <- ggplot(kernza_3_all, aes(y = GWP, x = Practice, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c ("aquamarine4", "aquamarine"))+
  labs(title = "Kernza", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  theme(plot.title = element_text(hjust = 0.5))
kernza_all_gwp


### SOC Bison ### South Dakota 

bison_3_regen_soc<- sum(all_data$dSOC[567:584])
bison_3_organic_soc<- sum(all_data$dSOC[585:602])

bison_3_regen_gwp<- sum(all_data$GWP[567:584])
bison_3_organic_gwp<- sum(all_data$GWP[585:602])

### Creating Data Frame and Plotting ###

bison_3_all <- data.frame(Practice = c("Regenerative", "Organic"),
                            SOC = c(bison_3_regen_soc, bison_3_organic_soc),
                            GWP = c(bison_3_regen_gwp, bison_3_organic_gwp))

### SOC ###

bison_all_soc <- ggplot(bison_3_all, aes(y = SOC, x = Practice, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c ("darkslategray", "darkseagreen4"))+
  labs(title = "Bison", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  theme(plot.title = element_text(hjust = 0.5))
bison_all_soc

### GWP ###

bison_all_gwp <- ggplot(bison_3_all, aes(y = GWP, x = Practice, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c ("darkslategray", "darkseagreen4"))+
  labs(title = "Bison", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  theme(plot.title = element_text(hjust = 0.5))
bison_all_gwp

### SOC Mango ### Nicaragua

mango_3_regen_soc <- sum(all_data$dSOC[639:656])
mango_3_organic_soc <- sum(all_data$dSOC[657:674])

mango_3_regen_gwp <- sum(all_data$GWP[639:656])
mango_3_organic_gwp <- sum(all_data$GWP[657:674])

### Creating Data Frame and Plotting ###

mango_3_all <- data.frame(Practice = c("Regenerative", "Organic"),
                            SOC = c(mango_3_regen_soc, mango_3_organic_soc),
                            GWP = c(mango_3_regen_gwp, mango_3_organic_gwp))

### SOC ###
mango_all_soc <- ggplot(mango_3_all, aes(y = SOC, x = Practice, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("darkorange4", "darkorange"))+
  labs(title = "Mango", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  theme(plot.title = element_text(hjust = 0.5))

mango_all_soc

### GWP ###
mango_all_gwp <- ggplot(mango_3_all, aes(y = GWP, x = Practice, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("darkorange4", "darkorange"))+
  labs(title = "Mango", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  theme(plot.title = element_text(hjust = 0.5))

mango_all_gwp

ggarrange(cotton_all_soc, kernza_all_soc, mango_all_soc, bison_all_soc)

ggarrange(cotton_all_gwp, kernza_all_gwp, mango_all_gwp, bison_all_gwp)


```


Graph #4 (Bar N2O $ CH4) TC
```{r}

options(scipen = 999)
# find the mean n2o and ch4 for regen and oragnic for each crop in the base site
# base sites 
# Kernza: Minnesota
# Mango: Nicaragua
# Cotton: Texas
# Bison: Sputh Dakota
kernza_regen_n2o<- sum(kernza$N2O_CO2e[55:72])
kernza_organic_n2o<- sum(kernza$N2O_CO2e[37:54])
kernza_regen_ch4<- sum(kernza$CH4_CO2e[55:72])
kernza_organic_ch4<- sum(kernza$CH4_CO2e[37:54])

mango_regen_n2o<- ((sum(mango$N2O_flux[37:54])/28)*66)*265
mango_organic_n2o<- ((sum(mango$N2O_flux[55:72])/28)*66)*265
mango_regen_ch4<- ((sum(mango$CH4[37:54])/12)*16)*28
mango_organic_ch4<- ((sum(mango$CH4[55:72])/12)*16)*28

cotton_regen_n2o<- sum(cotton$N2O[103:120])
cotton_organic_n2o<- sum(cotton$CH4[23:40])
cotton_regen_ch4<- sum(cotton$CH4[103:120])
cotton_oragnic_ch4<- sum(cotton$CH4[23:40])

bison_regen_n2o<- sum(bison$N2O_GWP[63:80])
bison_organic_n2o<- sum(bison$N2O_GWP[43:60])
bison_regen_ch4<- sum(bison$CH4_GWP[63:80])
bison_organic_ch4<- sum(bison$CH4_GWP[43:60])

# make a data set of these averages

n2o_ch4<- data.frame(Crop = c("Kernza", "Kernza", "Kernza", "Kernza", "Mango", "Mango","Mango", "Mango", "Cotton", "Cotton", "Cotton", "Cotton", "Bison", "Bison", "Bison", "Bison"),
                   Practice = c("Regenerative", "Organic", "Regenerative", "Organic", "Regenerative", "Organic", "Regenerative", "Organic"),
                   Gas = c("N2O", "N2O", "CH4", "CH4", "N2O", "N2O", "CH4", "CH4", "N2O", "N2O", "CH4", "CH4", "N2O", "N2O", "CH4", "CH4"),
                   kg_co2e = c(kernza_regen_n2o, kernza_organic_n2o, kernza_regen_ch4, kernza_organic_ch4, mango_regen_n2o, mango_organic_n2o, mango_regen_ch4, mango_organic_ch4, cotton_regen_n2o, cotton_organic_n2o, cotton_regen_ch4, cotton_oragnic_ch4, bison_regen_n2o, bison_organic_n2o, bison_regen_ch4, bison_organic_ch4))

ch4_n20_kernza<- n2o_ch4 %>% 
  filter(Crop == "Kernza") %>% 
  group_by(Practice)

ch4_n20_cotton<- n2o_ch4 %>% 
  filter(Crop == "Cotton") %>% 
  group_by(Practice)

ch4_n20_mango<- n2o_ch4 %>% 
  filter(Crop == "Mango") %>% 
  group_by(Practice)

ch4_n20_bison<- n2o_ch4 %>% 
  filter(Crop == "Bison") %>% 
  group_by(Practice)

ch4_n20_kernza_plot<- ggplot(ch4_n20_kernza, aes(y = kg_co2e, x = Gas, fill = Gas))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False", width = 0.5)+
  facet_wrap(~Practice)+
  scale_fill_manual(values = c("aquamarine4", "aquamarine"))+
  labs(title = "Kernza", y = "kgCO2e", x = element_blank())+
  theme_classic()
ch4_n20_kernza_plot

ch4_n20_cotton_plot<- ggplot(ch4_n20_cotton, aes(y = kg_co2e, x = Gas, fill = Gas))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False", width = 0.5)+
  facet_wrap(~Practice)+
  scale_fill_manual(values = c("deepskyblue4", "deepskyblue"))+
  labs(title = "Cotton", y = element_blank(), x = element_blank())+
  theme_classic()
ch4_n20_cotton_plot

ch4_n20_mango_plot<- ggplot(ch4_n20_mango, aes(y = kg_co2e, x = Gas, fill = Gas))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False", width = 0.5)+
  facet_wrap(~Practice)+
  scale_fill_manual(values = c("darkorange4", "darkorange"))+
  labs(title = "Mango", y = "kgCO2e", x = element_blank())+
  theme_classic()
ch4_n20_mango_plot

ch4_n20_bison_plot<- ggplot(ch4_n20_bison, aes(y = kg_co2e, x = Gas, fill = Gas))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False", width = 0.5)+
  facet_wrap(~Practice)+
  scale_fill_manual(values = c("darkslategray", "darkseagreen4"))+
  labs(title = "Bison", y = element_blank(), x = element_blank())+
  theme_classic()
ch4_n20_bison_plot

ggarrange(ch4_n20_kernza_plot, ch4_n20_cotton_plot, ch4_n20_mango_plot, ch4_n20_bison_plot)




# make a bar chart of the n2o_ch4 data frame

# Perform t-test on the bar chart to test fro significance


########
# do the t.test for all the N20 and CH4
#######

# KERNZA
kernza_regen_organic_n2o_t<- t.test(kernza$N2O_CO2e[55:72], kernza$N2O_CO2e[37:54])
kernza_regen_organic_n2o_t
kernza_regen_organic_ch4_t<- t.test(kernza$CH4_CO2e[55:72], kernza$CH4_CO2e[37:54])
kernza_regen_organic_ch4_t
# there is no significant difference between the N2O and CH4 impact between regen and organic for KERNZA

#COTTON
cotton_regen_organic_n20_t<- t.test(cotton$N2O[103:120], cotton$N2O[23:40])
cotton_regen_organic_n20_t
cotton_regen_organic_ch4_t<- t.test(cotton$CH4[103:120], cotton$CH4[23:40])
cotton_regen_organic_ch4_t
# there is a significant difference between the N20 and CH4 for regen and oragnic for COTTON


#MANGO 
mango_regen_organic_n20_t<- t.test(all_data$N2O_CO2e[639:656], all_data$N2O_CO2e[657:674])
mango_regen_organic_n20_t
mango_regen_organic_ch4_t<- t.test(all_data$CH4_CO2e[639:656], all_data$CH4_CO2e[657:674])
mango_regen_organic_ch4_t
# there was not a significant difference between n20 between regen and pragnic but there was a sognificant difference between ch4 regen and organic

# BISON
bison_regen_organic_n20<- t.test(bison$N2O_GWP[63:80], bison$N2O_GWP[43:60])
bison_regen_organic_n20
bison_regen_organic_ch4<- t.test(bison$CH4_GWP[63:80], bison$CH4_GWP[43:60])
bison_regen_organic_ch4
# there is a significant difference between regen and organic in N20 and CH4
```

Graph #5 (Bar Location) TC
```{r}
##############
# Kernza
#############
##### SOC
kernza_uk_regen_soc<- sum(kernza$dSOC[1:18])
kernza_uk_organic_soc<- sum(kernza$dSOC[19:36])

kernza_min_regen_soc<- sum(kernza$dSOC[55:72])
kernza_min_organic_soc<- sum(kernza$dSOC[37:54])

kernza_ks_regen_soc<- sum(kernza$dSOC[91:108])
kernza_ks_organic_soc<- sum(kernza$dSOC[73:90])

###### GWP

kernza_uk_regen_gwp<- sum(kernza$GWP[1:18])
kernza_uk_organic_gwp<- sum(kernza$GWP[19:36])

kernza_min_regen_gwp<- sum(kernza$GWP[55:72])
kernza_min_organic_gwp<- sum(kernza$GWP[37:54])

kernza_ks_regen_gwp<- sum(kernza$GWP[91:108])
kernza_ks_organic_gwp<- sum(kernza$GWP[73:90])

# making the data set

kernza_location<- data.frame(Location = c("Scotland", "Scotland","Minnesota", "Minnesota", "Kansas", "Kansas"),
                             Practice = c("Regenerative", "Organic","Regenerative", "Organic","Regenerative", "Organic"),
                             SOC = c(kernza_uk_regen_soc, kernza_uk_organic_soc, kernza_min_regen_soc, kernza_min_organic_soc, kernza_ks_regen_soc, kernza_ks_organic_soc),
                             GWP = c(kernza_uk_regen_gwp, kernza_uk_organic_gwp, kernza_min_regen_gwp, kernza_min_organic_gwp, kernza_ks_regen_gwp, kernza_ks_organic_gwp))

# plotting

kernza_location_soc_plot<- ggplot(kernza_location, aes(y = SOC, x = Location, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("aquamarine4", "aquamarine"))+
  labs(title = "Kernza", y = "kgSOC/ha", x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
kernza_location_soc_plot

kernza_location_gwp_plot<- ggplot(kernza_location, aes(y = GWP, x = Location, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("aquamarine4", "aquamarine"))+
  labs(title = "Kernza", y = "kgco2e", x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
kernza_location_gwp_plot

#########
# Cotton
########
###### SOC
cotton_china_regen_soc<- sum(cotton$dSOC[83:100])
cotton_china_organic_soc<- sum(cotton$dSOC[3:20])

cotton_india_regen_soc<- sum(cotton$dSOC[123:140])
cotton_india_organic_soc<- sum(cotton$dSOC[43:60])


cotton_texas_regen_soc<- sum(cotton$dSOC[103:120])
cotton_texas_organic_soc<- sum(cotton$dSOC[23:40])

cotton_peru_regen_soc<- sum(cotton$dSOC[143:160])
cotton_peru_organic_soc<- sum(cotton$dSOC[63:80])

######### GWP

cotton_china_regen_gwp<- sum(cotton$GWP[83:100])
cotton_china_organic_gwp<- sum(cotton$GWP[3:20])

cotton_india_regen_gwp<- sum(cotton$GWP[123:140])
cotton_india_organic_gwp<- sum(cotton$GWP[43:60])

cotton_texas_regen_gwp<- sum(cotton$GWP[103:120])
cotton_texas_organic_gwp<- sum(cotton$GWP[23:40])

cotton_peru_regen_gwp<- sum(cotton$GWP[143:160])
cotton_peru_organic_gwp<- sum(cotton$GWP[63:80])

# Making the data set

cotton_location<- data.frame(Location = c("China", "China","India", "India", "Texas", "Texas", "Peru", "Peru"),
                             Practice = c("Regenerative", "Organic","Regenerative", "Organic","Regenerative", "Organic", "Regenerative", "Organic"),
                             SOC = c(cotton_china_regen_soc, cotton_china_organic_soc, cotton_india_regen_soc, cotton_india_organic_soc, cotton_texas_regen_soc, cotton_texas_organic_soc, cotton_peru_regen_soc, cotton_peru_organic_soc),
                           GWP = c(cotton_china_regen_gwp, cotton_china_organic_gwp, cotton_india_regen_gwp, cotton_india_organic_gwp, cotton_texas_regen_gwp, cotton_texas_organic_gwp, cotton_peru_regen_gwp, cotton_peru_organic_gwp))

# Plotting

cotton_location_soc_plot<- ggplot(cotton_location, aes(y = SOC, x = Location, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("deepskyblue4", "deepskyblue"))+
  labs(title = "Cotton", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
cotton_location_soc_plot

cotton_location_gwp_plot<- ggplot(cotton_location, aes(y = GWP, x = Location, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("deepskyblue4", "deepskyblue"))+
  labs(title = "Cotton", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
cotton_location_gwp_plot

#######
# Mango
######
######## SOC
mango_india_regen_soc<- sum(mango$dSOC[1:18])
mango_india_organic_soc<- sum(mango$dSOC[19:36])

mango_nicaragua_regen_soc<- sum(mango$dSOC[37:54])
mango_nicaragua_organic_soc<- sum(mango$dSOC[55:72])

######## GWP

mango_india_regen_gwp<- sum(all_data$GWP[603:620])

mango_india_organic_gwp<- sum(all_data$GWP[621:638])

mango_nicaragua_regen_gwp<- sum(all_data$GWP[639:656])

mango_nicaragua_organic_gwp<- sum(all_data$GWP[657:674])

# Make the data set

mango_location<- data.frame(Location = c("India", "India","Nicaragua", "Nicaragua"),
                             Practice = c("Regenerative", "Organic","Regenerative", "Organic"),
                             SOC = c(mango_india_regen_soc, mango_india_organic_soc, mango_nicaragua_regen_soc, mango_nicaragua_organic_soc),
                           GWP = c(mango_india_regen_gwp, mango_india_organic_gwp, mango_nicaragua_regen_gwp, mango_nicaragua_organic_gwp))

# make the plots

mango_location_soc_plot<- ggplot(mango_location, aes(y = SOC, x = Location, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("darkorange4", "darkorange"))+
  labs(title = "Mango", y = "kgSOC/ha", x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
mango_location_soc_plot

mango_location_gwp_plot<- ggplot(mango_location, aes(y = GWP, x = Location, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("darkorange4", "darkorange"))+
  labs(title = "Mango", y = "kgCO2e", x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
mango_location_gwp_plot

##################
# Bison
##################

bison_sd_regen_soc<- sum(bison$dSOC[63:80])
bison_sd_organic_soc<- sum(bison$dSOC[45:60])

bison_bz_regen_soc<- sum(bison$dSOC[23:40])
bison_bz_organic_soc<- sum(bison$dSOC[3:20])

bison_sd_regen_gwp<- sum(bison$GWP[63:80])
bison_sd_organic_gwp<- sum(bison$GWP[45:60])

bison_bz_regen_gwp<- sum(bison$GWP[23:40])
bison_bz_organic_gwp<- sum(bison$GWP[3:20])

# make the dataset
bison_location<- data.frame(Location = c("South Dakota", "South Dakota","Brazil", "Brazil"),
                             Practice = c("Regenerative", "Organic","Regenerative", "Organic"),
                             SOC = c(bison_sd_regen_soc, bison_sd_organic_soc, bison_bz_regen_soc, bison_bz_organic_soc),
                           GWP = c(bison_sd_regen_gwp, bison_sd_organic_gwp, bison_bz_regen_gwp, bison_bz_organic_gwp))

# make the plots

bison_location_soc_plot<- ggplot(bison_location, aes(y = SOC, x = Location, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("darkslategray", "darkseagreen4"))+
  labs(title = "Bison", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
bison_location_soc_plot

bison_location_gwp_plot<- ggplot(bison_location, aes(y = GWP, x = Location, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("darkslategray", "darkseagreen4"))+
  labs(title = "Bison", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
bison_location_gwp_plot

# accumilate the plots
location_soc_plots<- ggarrange(kernza_location_soc_plot, cotton_location_soc_plot, mango_location_soc_plot, bison_location_soc_plot)

location_soc_plots

location_gwp_plots<- ggarrange(kernza_location_gwp_plot, cotton_location_gwp_plot, mango_location_gwp_plot, bison_location_gwp_plot)

location_soc_plots
location_gwp_plots

########
# Perform t-tests for location differences
#######
# KERNZA
kernza_kansas_min_regen_soc_t<- t.test(kernza$dSOC[91:108], kernza$dSOC[55:72])
kernza_kansas_min_regen_soc_t
kernza_kansas_uk_regen_soc_t<- t.test(kernza$dSOC[91:108], kernza$dSOC[1:18])
kernza_kansas_uk_regen_soc_t
kernza_uk_min_regen_soc_t<- t.test(kernza$dSOC[1:18], kernza$dSOC[55:72])
kernza_uk_min_regen_soc_t
# under regenerative practices all of the sites are significantly fdifferent SOC values for kernza

kernza_kansas_min_regen_gwp_t<- t.test(kernza$GWP[91:108], kernza$GWP[55:72])
kernza_kansas_min_regen_gwp_t
kernza_kansas_uk_regen_gwp_t<- t.test(kernza$GWP[91:108], kernza$GWP[1:18])
kernza_kansas_uk_regen_gwp_t
kernza_uk_min_regen_gwp_t<- t.test(kernza$GWP[1:18], kernza$GWP[55:72])
kernza_uk_min_regen_gwp_t
# under regenerative practices all of the sites are significantly fdifferent GWP values for kernza


kernza_kansas_min_regen_soc_t<- t.test(kernza$dSOC[73:90], kernza$dSOC[37:54])
kernza_kansas_min_regen_soc_t
kernza_kansas_uk_regen_soc_t<- t.test(kernza$dSOC[73:90], kernza$dSOC[19:36])
kernza_kansas_uk_regen_soc_t
kernza_uk_min_regen_soc_t<- t.test(kernza$dSOC[19:36], kernza$dSOC[37:54])
kernza_uk_min_regen_soc_t
# under organic practices all of the sites are significantly fdifferent SOC values for kernza


kernza_kansas_min_regen_gwp_t<- t.test(kernza$GWP[73:90], kernza$GWP[37:54])
kernza_kansas_min_regen_gwp_t
kernza_kansas_uk_regen_gwp_t<- t.test(kernza$GWP[73:90], kernza$GWP[19:36])
kernza_kansas_uk_regen_gwp_t
kernza_uk_min_regen_gwp_t<- t.test(kernza$GWP[19:36], kernza$GWP[37:54])
kernza_uk_min_regen_gwp_t
# under organic practices all of the sites are significantly fdifferent GWP values for kernza

# COTTON
cotton_peru_china_regen_soc_t<- t.test(cotton$dSOC[143:160], cotton$dSOC[83:100])
cotton_peru_china_regen_soc_t
cotton_peru_india_regen_soc_t<- t.test(cotton$dSOC[143:160], cotton$dSOC[143:160])
cotton_peru_india_regen_soc_t
cotton_peru_texas_regen_soc_t<- t.test(cotton$dSOC[143:160], cotton$dSOC[103:120])
cotton_peru_texas_regen_soc_t
cotton_china_india_regen_soc_t<- t.test(cotton$dSOC[83:100], cotton$dSOC[123:140])
cotton_china_india_regen_soc_t
cotton_china_texas_regen_soc_t<- t.test(cotton$dSOC[83:100], cotton$dSOC[103:120])
cotton_china_texas_regen_soc_t
cotton_india_texas_regen_soc_t<- t.test(cotton$dSOC[123:140], cotton$dSOC[103:120])
cotton_india_texas_regen_soc_t
# peru and india are not significantly different and China and India are not significantly different

# test for GWP
cotton_peru_china_regen_gwp_t<- t.test(cotton$GWP[143:160], cotton$GWP[83:100])
cotton_peru_china_regen_gwp_t
cotton_peru_india_regen_gwp_t<- t.test(cotton$GWP[143:160], cotton$GWP[143:160])
cotton_peru_india_regen_gwp_t
cotton_peru_texas_regen_gwp_t<- t.test(cotton$GWP[143:160], cotton$GWP[103:120])
cotton_peru_texas_regen_gwp_t
cotton_china_india_regen_gwp_t<- t.test(cotton$GWP[83:100], cotton$GWP[123:140])
cotton_china_india_regen_gwp_t
cotton_china_texas_regen_gwp_t<- t.test(cotton$GWP[83:100], cotton$GWP[103:120])
cotton_china_texas_regen_gwp_t
cotton_india_texas_regen_gwp_t<- t.test(cotton$GWP[123:140], cotton$GWP[103:120])
cotton_india_texas_regen_gwp_t
# There is not a sognigicatn difference between the GWP for Peru and India for cotton but besides that all are significantly different


# MANGO
mango_nic_india_regen_soc_t<- t.test(mango$dSOC[37:54], mango$dSOC[1:18])
mango_nic_india_regen_soc_t
mango_nic_india_organic_soc_t<- t.test(mango$dSOC[55:72], mango$dSOC[19:36])
mango_nic_india_organic_soc_t
# there is no significatn difference between the SOC for regen or organic in India or Nicaragua for mangos

mango_nic_india_regen_gwp_t<- t.test(all_data$GWP[639:656], all_data$GWP[603:620])
mango_nic_india_regen_gwp_t
mango_nic_india_organic_gwp_t<- t.test(all_data$GWP[657:674], all_data$GWP[621:638])
mango_nic_india_organic_gwp_t
# there is not a significant difference between India and Nicaragua GWP in regenerative or organic 


#BISON
bison_sd_bz_regen_soc_t<- t.test(bison$dSOC[63:80], bison$dSOC[23:40])
bison_sd_bz_regen_soc_t
bison_sd_bz_organic_soc_t<- t.test(bison$dSOC[45:60], bison$dSOC[3:20])
bison_sd_bz_organic_soc_t
# there is a significant difference between South Dakota and Brazil for regen and organic on SOC output

bison_sd_bz_regen_gwp_t<- t.test(bison$GWP[63:80], bison$GWP[23:40])
bison_sd_bz_regen_gwp_t
bison_sd_bz_organic_gwp_t<- t.test(bison$GWP[45:60], bison$GWP[3:20])
bison_sd_bz_organic_gwp_t
# there is a significant difference in South Dakota and Brazil GWP for regen

```

Graph #6 (Bar Climate) TC
```{r}

cotton_india_regen_soc
cotton_india_organic_soc
cotton_nc_regen_soc<- sum(all_data$dSOC[307:324])
cotton_nc_organic_soc<- sum(cotton_climate_organic$dSOC[3:20])
cotton_climate<- data.frame(Practice = c("Regenerative", "Regenerative", "Organic", "Organic"),
                            Climate = c("India", "No Climate", "India", "No Climate"),
                            SOC = c(cotton_india_regen_soc, cotton_nc_regen_soc, cotton_india_organic_soc, cotton_nc_organic_soc))


kernza_min_regen_soc
kernza_min_organic_soc
kernza_nc_regen_soc<- sum(kernza_updated$dSOC[127:144])
kernza_nc_organic_soc<- sum(kernza_updated$dSOC[109:126])
kernza_climate<- data.frame(Practice = c("Regenerative", "Regenerative", "Organic", "Organic"),
                            Climate = c("Minnesota", "No Climate", "Minnesota", "No Climate"),
                            SOC = c(kernza_min_regen_soc, kernza_nc_regen_soc, kernza_min_organic_soc, kernza_nc_organic_soc))

mango_nicaragua_regen_soc
mango_nicaragua_organic_soc
mango_nc_regen_soc<- sum(mango_nc$dSOC[63:80])
mango_nc_organic_soc<- sum(mango_nc$dSOC[43:60])
mango_climate<- data.frame(Practice = c("Regenerative", "Regenerative", "Organic", "Organic"),
                            Climate = c("Nicaragua", "No Climate", "Nicaragua", "No Climate"),
                            SOC = c(mango_nicaragua_regen_soc, mango_nc_regen_soc, mango_nicaragua_organic_soc, mango_nc_organic_soc))

bison_sd_regen_soc
bison_sd_organic_soc
bison_nc_regen_soc<- sum(bison_nc$dSOC[3:20])
bison_nc_organic_soc<- sum(bison_nc$dSOC[23:40])
bison_climate<- data.frame(Practice = c("Regenerative", "Regenerative", "Organic", "Organic"),
                            Climate = c("South Dakota", "No Climate", "South Dakota", "No Climate"),
                            SOC = c(bison_sd_regen_soc, bison_nc_regen_soc, bison_sd_organic_soc, bison_nc_organic_soc))

# Make the plot for the differen crops for SOC

kernza_climate_soc_plot<- ggplot(kernza_climate, aes(y = SOC, x = Climate, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("aquamarine4", "aquamarine"))+
  labs(title = "Kernza", y = "kgSOC/ha", x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
kernza_climate_soc_plot

cotton_climate_soc_plot<- ggplot(cotton_climate, aes(y = SOC, x = Climate, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("deepskyblue4", "deepskyblue"))+
  labs(title = "Cotton", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
cotton_climate_soc_plot

mango_climate_soc_plot<- ggplot(mango_climate, aes(y = SOC, x = Climate, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("darkorange4", "darkorange"))+
  labs(title = "Mango", y = "kgSOC/ha", x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
mango_climate_soc_plot


bison_climate_soc_plot<- ggplot(bison_climate, aes(y = SOC, x = Climate, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("darkslategray", "darkseagreen4"))+
  labs(title = "Bison", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
bison_climate_soc_plot

ggarrange(kernza_climate_soc_plot, cotton_climate_soc_plot, mango_climate_soc_plot, bison_climate_soc_plot)
  

###### Do the same for GWP

cotton_india_regen_gwp
cotton_india_organic_gwp
cotton_nc_regen_gwp<- sum(all_data$GWP[307:324])
cotton_nc_organic_gwp<- sum(cotton_climate_organic$GWP[3:20])
cotton_climate_gwp<- data.frame(Practice = c("Regenerative", "Regenerative", "Organic", "Organic"),
                            Climate = c("India", "No Climate", "India", "No Climate"),
                            GWP = c(cotton_india_regen_gwp, cotton_nc_regen_gwp, cotton_india_organic_gwp, cotton_nc_organic_gwp))


kernza_min_regen_gwp
kernza_min_organic_gwp
kernza_nc_regen_gwp<- sum(kernza_updated$GWP[127:144])
kernza_nc_organic_gwp<- sum(kernza_updated$GWP[109:126])
kernza_climate_gwp<- data.frame(Practice = c("Regenerative", "Regenerative", "Organic", "Organic"),
                            Climate = c("Minnesota", "No Climate", "Minnesota", "No Climate"),
                            GWP = c(kernza_min_regen_gwp, kernza_nc_regen_gwp, kernza_min_organic_gwp, kernza_nc_organic_gwp))

mango_nicaragua_regen_gwp
mango_nicaragua_organic_gwp

mango_nc_regen_gwp<- (sum(mango_nc$GWP[62:80]))

mango_nc_organic_gwp<- (sum(mango$GWP[43:60]))


mango_climate_gwp<- data.frame(Practice = c("Regenerative", "Regenerative", "Organic", "Organic"),
                            Climate = c("Nicaragua", "No Climate", "Nicaragua", "No Climate"),
                            GWP = c(mango_nicaragua_regen_gwp, mango_nc_regen_gwp, mango_nicaragua_organic_gwp, mango_nc_organic_gwp))

bison_sd_regen_gwp
bison_sd_organic_gwp
bison_nc_regen_gwp<- sum(bison_nc$GWP[3:20])
bison_nc_organic_gwp<- sum(bison_nc$GWP[23:40])
bison_climate_gwp<- data.frame(Practice = c("Regenerative", "Regenerative", "Organic", "Organic"),
                            Climate = c("South Dakota", "No Climate", "South Dakota", "No Climate"),
                            GWP = c(bison_sd_regen_gwp, bison_nc_regen_gwp, bison_sd_organic_gwp, bison_nc_organic_gwp))


# now make the plots for climate sensativity on GWP

kernza_climate_gwp_plot<- ggplot(kernza_climate_gwp, aes(y = GWP, x = Climate, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("aquamarine4", "aquamarine"))+
  labs(title = "Kernza", y = "kgCO2e/ha", x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
kernza_climate_gwp_plot

cotton_climate_gwp_plot<- ggplot(cotton_climate_gwp, aes(y = GWP, x = Climate, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("deepskyblue4", "deepskyblue"))+
  labs(title = "Cotton", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
cotton_climate_gwp_plot

mango_climate_gwp_plot<- ggplot(mango_climate_gwp, aes(y = GWP, x = Climate, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("darkorange4", "darkorange"))+
  labs(title = "Mango", y = "kgSOC/ha", x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
mango_climate_gwp_plot


bison_climate_gwp_plot<- ggplot(bison_climate_gwp, aes(y = GWP, x = Climate, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("darkslategray", "darkseagreen4"))+
  labs(title = "Bison", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
bison_climate_gwp_plot

ggarrange(kernza_climate_soc_plot, cotton_climate_soc_plot, mango_climate_soc_plot, bison_climate_soc_plot)

ggarrange(kernza_climate_gwp_plot, cotton_climate_gwp_plot, mango_climate_gwp_plot, bison_climate_gwp_plot)


##########
# Perform t- tests
##########

# KERNZA
kernza_climate_regen_soc_t<- t.test(kernza$dSOC[55:72], kernza_updated$dSOC[127:144])
kernza_climate_regen_soc_t # there is a sognificant difference between Kernza regen SOC with Minnesota climate and with Shangila climate

kernza_climate_organic_soc_t<-t.test(kernza$dSOC[37:54],kernza_updated$dSOC[109:126])
kernza_climate_organic_soc_t# there is a sognificant difference between Kernza organic SOC with Minnesota climate and with Shangila climate

kernza_climate_regen_gwp_t<- t.test(kernza$GWP[55:72], kernza_updated$GWP[127:144])
kernza_climate_regen_gwp_t# there is a sognificant difference between Kernza regen GWP with Minnesota climate and with Shangila climate

kernza_climate_organic_gwp_t<- t.test(kernza$GWP[37:54], kernza_updated$GWP[109:126])
kernza_climate_organic_gwp_t# there is a sognificant difference between Kernza organic GWP with Minnesota climate and with Shangila climate

# COTTON
cotton_climate_regen_soc_t<- t.test(cotton$dSOC[123:140], all_data$dSOC[307:324])
cotton_climate_regen_soc_t # there is a sognificant difference between Cotton regen SOC with India climate and with Shangila climate

cotton_climate_regen_gwp_t<- t.test(cotton$GWP[123:140], all_data$GWP[307:324])
cotton_climate_regen_gwp_t # there is a sognificant difference between Cotton regen GWP with India climate and with Shangila climate

# MANGO
mango_climate_regen_soc_t<- t.test(mango$dSOC[37:54], mango_nc$dSOC[63:80])
mango_climate_regen_soc_t# there is a sognificant difference between Mango regen SOC with Nicaragua climate and with Shangila climate

mango_climate_organic_soc_t<- t.test(mango$dSOC[37:54], mango_nc$dSOC[63:80])
mango_climate_organic_soc_t# there is a sognificant difference between Mango regen SOC with Nicaragua climate and with Shangila climate

mango_climate_regen_gwp_t<- t.test(all_data$GWP[37:54], all_data$GWP[63:80])
mango_climate_regen_gwp_t# there is a sognificant difference between Mango organic GWP with Nicaragua climate and with Shangila climate

mango_climate_organic_gwp_t<- t.test(all_data$GWP[37:54], all_data$GWP[63:80])
mango_climate_organic_gwp_t  # there is a sognificant difference between Mango organic GWP with Nicaragua climate and with Shangila climate

# BISON
bison_climate_regen_soc_t<- t.test(bison$dSOC[63:80], bison_nc$dSOC[3:20])
bison_climate_regen_soc_t# there is a sognificant difference between Bison regen SOC with SD climate and with Shangila climate

bison_climate_organic_soc_t<- t.test(bison$dSOC[45:60], bison_nc$dSOC[23:40])
bison_climate_organic_soc_t# there is a sognificant difference between Bison organic SOC with SD climate and with Shangila climate

bison_climate_regen_gwp_t<- t.test(bison$GWP[63:80], bison_nc$GWP[3:20])
bison_climate_regen_gwp_t# there is a sognificant difference between Bison regen GWP with SD climate and with Shangila climate

bison_climate_organic_gwp_t<- t.test(bison$GWP[45:60], bison_nc$GWP[23:40])
bison_climate_organic_gwp_t# there is a sognificant difference between Bison organic GWP with SD climate and with Shangila climate

```


Graph #7 (Bar compost/manure sensitivity) ID
```{r, fig.height=3, fig.width=4}

cotton_manure_s<- sum(all_data$dSOC[217:234])
bison_compost_s<-sum(all_data$dSOC[585:602])
kernza_compost_s<-sum(all_data$dSOC[55:72])
mango_compost_s<-sum(mango_compost$dSOC[1:18])

cotton_nomanure_s<-sum(all_data$dSOC[343:360])
bison_nocompost_s<-sum(bison_nocompost$dSOC[3:20])
kernza_nocompost_s<-sum(kernza_compost$dSOC[3:20])
mango_nocompost_s<-sum(mango_compost$dSOC[37:54])


cotton_manure_g<- sum(all_data$GWP[217:234])
bison_compost_g<-sum(all_data$GWP[585:602])
kernza_compost_g<-sum(all_data$GWP[55:72])
mango_compost_g<-sum(mango_compost$GWP[1:18])

cotton_nomanure_g<-sum(all_data$GWP[343:360])
bison_nocompost_g<-sum(bison_nocompost$GWP[3:20])
kernza_nocompost_g<-sum(kernza_compost$GWP[3:20])
mango_nocompost_g<-sum(mango_compost$GWP[37:54])




nutrient_data<- data.frame(Crop = c("Cotton", "Cotton", "Bison", "Bison", "Mango", "Mango","Kernza Wheat", "Kernza Wheat"),
                   Practice = c("Regenerative", "Regenerative-Nutrient", "Regenerative", "Regenerative-Nutrient", "Regenerative", "Regenerative-Nutrient", "Regenerative", "Regenerative-Nutrient"),
                   GWP = c(cotton_manure_g, cotton_nomanure_g,bison_compost_g, bison_nocompost_g,mango_compost_g, mango_nocompost_g, kernza_compost_g, kernza_nocompost_g),
                   SOC=c(cotton_manure_s, cotton_nomanure_s,bison_compost_s, bison_nocompost_s,mango_compost_s, mango_nocompost_s, kernza_compost_s, kernza_nocompost_s)) %>% 
  group_by(Practice)


nutrient_SOC<- ggplot(nutrient_data, aes(y = SOC, x = Practice, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False")+
  facet_wrap(~Crop)+
  scale_fill_manual(values = c("darkorchid4", "darkorange2"))+
  labs(y ="Total Change in SOC(kg/ha)", title = "Sensitivity Analysis of Nutrient Management: Total Change in SOC")+
  theme_classic()

nutrient_SOC


nutrient_GWP<- ggplot(nutrient_data, aes(y = GWP, x = Practice, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False")+
  facet_wrap(~Crop)+
  scale_fill_manual(values = c("darkorchid4", "darkorange2"))+
  labs(y ="kg CO2e/ha", title = "Sensitivity Analysis of Nutrient Management: Total Change in Global Warming Potential ")+
  theme_classic()

nutrient_GWP



              


```

Graph #8 (Bar crop sensitivity) ID
```{r, fig.height=6, fig.width=6}
cotton_mono_s<- sum(all_data$dSOC[361:378])
cotton_two_s<-sum(all_data$dSOC[379:396])
cotton_three_s<-sum(all_data$dSOC[397:414])
cotton_four_s<-sum(all_data$dSOC[415:432])
cotton_regen_india_s<- sum(all_data$dSOC[217:234])


bison_mono_s<- sum(bison_crop$dSOC[23:40])
bison_two_s<-sum(bison_crop$dSOC[43:60])
bison_three_s<-sum(bison_crop$dSOC[63:803])
bison_four_s<-sum(bison_crop$dSOC[83:100])
bison_sd_s<- sum(all_data$dSOC[103:120])

mango_mono_s<- sum(mango_crops$dSOC[37:54])
mango_two_s<-sum(mango_crops$dSOC[19:36])
mango_regen_s<-sum(mango_crops$dSOC[1:18])


kernza_mono_s<- sum(kernza_updated$dSOC[1:18])
kernza_two_s<-sum(kernza_updated$dSOC[55:72])
kernza_three_s<-sum(kernza_updated$dSOC[91:108])


cotton_mono_g<- sum(all_data$GWP[361:378])
cotton_two_g<-sum(all_data$GWP[379:396])
cotton_three_g<-sum(all_data$GWP[397:414])
cotton_four_g<-sum(all_data$GWP[415:432])
cotton_regen_india_g<- sum(all_data$GWP[217:234])


bison_mono_g<- sum(bison_crop$GWP[23:40])
bison_two_g<-sum(bison_crop$GWP[43:60])
bison_three_g<-sum(bison_crop$GWP[63:80])
bison_four_g<-sum(bison_crop$GWP[83:100])
bison_sd_g<- sum(all_data$GWP[103:120])

mango_mono_g<- sum(mango_crops$GWP[37:54])
mango_two_g<-sum(mango_crops$GWP[20:3])
mango_regen_g<-sum(mango_crops$GWP[1:18])

kernza_mono_g<- sum(kernza_updated$GWP[1:18])
kernza_two_g<-sum(kernza_updated$GWP[55:72])
kernza_three_g<-sum(kernza_updated$GWP[91:108])

cropping_data<- data.frame(Country = c("India", "India","India", "India","India","South Dakota", "South Dakota","South Dakota", "South Dakota","South Dakota", "Nicaragua", "Nicaragua", "Nicaragua", "Minnesota","Minnesota", "Minnesota"),
                   Crop = c("Cotton", "Two Crops", "Three Crops", "Four Crops", "Regenerative", "Grass", "Two Crops", "Three Crops","Four Crops", "Regenerative", "Mango", "Two Crops","Regenerative","Kernza Wheat", "Two Crops", "Regenerative"),
                   GWP = c(cotton_mono_g, cotton_two_g,cotton_three_g, cotton_four_g,cotton_regen_india_g, bison_mono_g, bison_two_g, bison_three_g, bison_four_g,bison_sd_g, mango_mono_g,mango_two_g,mango_regen_g,kernza_mono_g, kernza_two_g,kernza_three_g),
                   SOC=c(cotton_mono_s, cotton_two_s,cotton_three_s, cotton_four_s,cotton_regen_india_s, bison_mono_s, bison_two_s, bison_three_s, bison_four_s,bison_sd_s, mango_mono_s,mango_two_s,mango_regen_s,kernza_mono_s, kernza_two_s,kernza_three_s)) %>% 
  group_by(Country)


              

cropping_data_cotton<-cropping_data %>% 
  filter(Country=="India")

cropping_data_cotton$Crop <- factor(cropping_data_cotton$Crop,levels = c("Cotton", "Two Crops", "Three Crops", "Four Crops", "Regenerative"))
  
crop_sens_SOC_india<- ggplot(cropping_data_cotton, aes(y = SOC, x = Crop, fill = Crop))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False")+
  labs(y ="Total Change in SOC(kg/ha)", title= "Cotton in India",x= "Cropping structure")+
  theme_classic()

crop_sens_SOC_india

cropping_data_bison<-cropping_data %>% 
  filter(Country=="South Dakota")

cropping_data_bison$Crop <- factor(cropping_data_bison$Crop,levels = c("Grass", "Two Crops", "Three Crops", "Four Crops", "Regenerative"))
  
crop_sens_SOC_sd<- ggplot(cropping_data_bison, aes(y = SOC, x = Crop, fill = Crop))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False")+
  labs(y ="Total Change in SOC(kg/ha)", title= "Grazing in South Dakota",x= "Cropping structure")+
  theme_classic()

crop_sens_SOC_sd

cropping_data_mango<-cropping_data %>% 
  filter(Country=="Nicaragua")

cropping_data_mango$Crop <- factor(cropping_data_mango$Crop,levels = c("Mango", "Two Crops", "Three Crops", "Regenerative"))

crop_sens_SOC_nic<- ggplot(cropping_data_mango, aes(y = SOC, x = Crop, fill = Crop))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False")+
  labs(y ="Total Change in SOC(kg/ha)", title="Mango in Nicaragua",x= "Cropping structure")+
  theme_classic()

crop_sens_SOC_nic

cropping_data_kernza<-cropping_data %>% 
  filter(Country=="Minnesota")

cropping_data_kernza$Crop <- factor(cropping_data_kernza$Crop,levels = c("Kernza Wheat", "Two Crops", "Three Crops", "Regenerative"))

crop_sens_SOC_mn<- ggplot(cropping_data_kernza, aes(y = SOC, x = Crop, fill = Crop))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False")+
  labs(y ="Total Change in SOC(kg/ha)", title="Kernza Wheat in Minnesota",x= "Cropping structure")+
  theme_classic()

crop_sens_SOC_mn



crop_sens_gwp_india<- ggplot(cropping_data_cotton, aes(y = GWP, x = Crop, fill = Crop))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False")+
  labs(y ="kg CO2e/ha", title= "Cotton in India",x= "Cropping structure")+
  theme_classic()

crop_sens_gwp_india


crop_sens_gwp_sd<- ggplot(cropping_data_bison, aes(y = GWP, x = Crop, fill = Crop))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False")+
  labs(y ="kg CO2e/ha", title= "Grazing in South Dakota",x= "Cropping structure")+
  theme_classic()

crop_sens_gwp_sd

crop_sens_gwp_nic<- ggplot(cropping_data_mango, aes(y = GWP, x = Crop, fill = Crop))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False")+
  labs(y ="kg CO2e/ha", title= "Mango in Nicaragua",x= "Cropping structure")+
  theme_classic()

crop_sens_gwp_nic

crop_sens_gwp_mn<- ggplot(cropping_data_kernza, aes(y = GWP, x = Crop, fill = Crop))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False")+
  labs(y ="kg CO2e/ha", title= "Kernza Wheat in Minnesota", x= "Cropping structure")+
  theme_classic()

crop_sens_gwp_mn

ggarrange(crop_sens_gwp_india,crop_sens_gwp_sd,crop_sens_gwp_nic,crop_sens_gwp_mn)


ggarrange(crop_sens_SOC_india,crop_sens_SOC_sd,crop_sens_SOC_nic,crop_sens_SOC_mn)

```

Graph #9 (Bar tillage sensitivity) ID
```{r, fig.height=3, fig.width=4}

cotton_tillage<-cotton %>% 
  filter(Practice=="Tillage"| Practice=="Regenerative")



cotton_regen_india_nt_s<- sum(all_data$dSOC[217:234])
cotton_regen_china_nt_s<-sum(all_data$dSOC[181:198])
cotton_regen_texas_nt_s<-sum(all_data$dSOC[199:216])
cotton_regen_peru_nt_s<-sum(all_data$dSOC[235:252])

cotton_till_india_s<-sum(all_data$dSOC[325:342])
cotton_till_china_s<-sum(all_data$dSOC[477:494])
cotton_till_texas_s<-sum(all_data$dSOC[513:530])
cotton_till_peru_s<-sum(all_data$dSOC[495:512])


bison_regen_ch4<- mean(bison$CH4_GWP[63:80])


cotton_regen_india_nt_g<- sum(all_data$GWP[217:234])
cotton_regen_china_nt_g<-sum(all_data$GWP[181:198])
cotton_regen_texas_nt_g<-sum(all_data$GWP[199:216])
cotton_regen_peru_nt_g<-sum(all_data$GWP[235:252])

cotton_till_india_g<-sum(all_data$GWP[325:342])
cotton_till_china_g<-sum(all_data$GWP[477:494])
cotton_till_texas_g<-sum(all_data$GWP[513:530])
cotton_till_peru_g<-sum(all_data$GWP[495:512])

tillage_data<- data.frame(Country = c("India", "India", "China", "China", "Texas", "Texas","Peru", "Peru"),
                   Practice = c("Regenerative", "Regenerative+Tillage", "Regenerative", "Regenerative+Tillage", "Regenerative", "Regenerative+Tillage", "Regenerative", "Regenerative+Tillage"),
                   GWP = c(cotton_regen_india_nt_g, cotton_till_india_g,cotton_regen_china_nt_g, cotton_till_china_g,cotton_regen_texas_nt_g, cotton_till_texas_g, cotton_regen_peru_nt_g, cotton_till_peru_g),
                   SOC=c(cotton_regen_india_nt_s, cotton_till_india_s,cotton_regen_china_nt_s, cotton_till_china_s,cotton_regen_texas_nt_s, cotton_till_texas_s, cotton_regen_peru_nt_s, cotton_till_peru_s)) %>% 
  group_by(Practice)
              


tillage_SOC<- ggplot(tillage_data, aes(y = SOC, x = Practice, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False")+
  facet_wrap(~Country)+
  scale_fill_manual(values = c("darkorchid4", "darkorange2"))+
  labs(y ="Total Change in SOC(kg/ha)", title = "Sensitivity Analysis of Tillage: Total Change in SOC ")+
  theme_classic()

tillage_SOC


tillage_GWP<- ggplot(tillage_data, aes(y = GWP, x = Practice, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False")+
  facet_wrap(~Country)+
  scale_fill_manual(values = c("darkorchid4", "darkorange2"))+
  labs(y ="kg CO2e/ha", title = "Sensitivity Analysis of Tillage: Total Change in Global Warming Potential ")+
  theme_classic()

tillage_GWP



```

Save Graphs as jpg
```{r}


```

